SECURITY_EVENTS: list[str] = [
    # cd tracee/signatures/go && grep -r "EventName:" --exclude="*_test.go" * | cut -d'"' -f2 | sort -u
    "anti_debugging",
    "aslr_inspection",
    "cgroup_notify_on_release",
    "cgroup_release_agent",
    "core_pattern_modification",
    "default_loader_mod",
    "disk_mount",
    "docker_abuse",
    "dropped_executable",
    "dynamic_code_loading",
    "fileless_execution",
    "hidden_file_created",
    "illegitimate_shell",
    "k8s_api_connection",
    "k8s_cert_theft",
    # Error: invalid event to trace: k8s_service_account_token
    # "k8s_service_account_token",
    "kernel_module_loading",
    "ld_preload",
    "proc_fops_hooking",
    "proc_kcore_read",
    "proc_mem_access",
    "proc_mem_code_injection",
    "process_vm_write_inject",
    "ptrace_code_injection",
    "rcd_modification",
    "sched_debug_recon",
    "scheduled_task_mod",
    "stdio_over_socket",
    "sudoers_modification",
    "syscall_hooking",
    "system_request_key_mod",
    # non signature related but still security related
    "hidden_kernel_module",
    "bpf_attach",
    "ftrace_hook",
    "hooked_syscall",
]
